/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import agh.project.util.LameBDparser;
import java.io.File;
import java.util.ArrayList;
import org.apache.log4j.Logger;
import javax.swing.JFileChooser;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import org.apache.log4j.PropertyConfigurator;
import enigma2gui.Enigma2Gui;

/**
 *
 * @author patlas
 */
public class GUI extends javax.swing.JFrame {

    String fName = null;
    Enigma2Gui enigma2gui = null;
    final static Logger logger = Logger.getLogger(GUI.class);
    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        //fillTree();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        enigmaTree = new javax.swing.JTree();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("root");
        enigmaTree.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane1.setViewportView(enigmaTree);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        JFileChooser fileChooser = new JFileChooser();
        int returnValue = fileChooser.showOpenDialog(null);
        if (returnValue == JFileChooser.APPROVE_OPTION) {
          File selectedFile = fileChooser.getSelectedFile();
          fName = selectedFile.getPath();
        }
        
        ArrayList<ArrayList<String>> trans,channels = null;
        
        trans =  new LameBDparser(fName).getTransponders();
        
        System.out.println(trans.get(0).get(0));
        System.out.println(trans.get(0).get(1));
        System.out.println(trans.get(0).get(2));
        System.out.println(trans.get(0).get(3));
        System.out.println(trans.get(0).get(4));
        
        System.out.println(trans.get(1).get(0));
        System.out.println(trans.get(2).get(0));
        
        channels = new LameBDparser(fName).getChannels();
        
        System.out.println(channels.get(0).get(2));
        System.out.println(channels.get(1).get(2));
        System.out.println(channels.get(2).get(2));
        System.out.println(channels.get(300).get(2));
        
        enigma2gui = new Enigma2Gui(enigmaTree);
        enigma2gui.addTranspondersToTree(trans);
        enigma2gui.addChannellsToTransponders(channels);
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    public void fillTree(){
        
        DefaultMutableTreeNode root = new DefaultMutableTreeNode( "Deck" );

        DefaultMutableTreeNode itemClubs = new DefaultMutableTreeNode( "Clubs" );
        root.add( itemClubs );

        DefaultMutableTreeNode itemDiamonds = new DefaultMutableTreeNode( "Diamonds" );
        root.add( itemDiamonds );
        
        DefaultTreeModel treeModel = new DefaultTreeModel( root );
        
        itemDiamonds.add(new DefaultMutableTreeNode("test"));
        
        enigmaTree.setModel(treeModel);
        enigmaTree.setRootVisible(false);
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
        PropertyConfigurator.configure("log4j.properties");
        
        /* Create and display the form */
        logger.info("GUI has been started");
        

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTree enigmaTree;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
